apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terminated-pod-gc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terminated-pod-gc
subjects:
  - kind: ServiceAccount
    name: terminated-pod-gc
    namespace: kube-system
